# Generated by Django 5.2.7 on 2026-05-03 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cv_text", models.TextField()),
                ("job_description", models.TextField()),
                ("match_score", models.IntegerField()),
                ("matched_skills", models.TextField()),
                ("missing_skills", models.TextField()),
                ("improvement_tips", models.TextField()),
                ("summary", models.TextField()),
                ("cv_rewrite_requested", models.BooleanField(default=False)),
                ("rewritten_cv", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
