# Generated by Django 5.2.7 on 2026-05-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumeApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="cover_letter",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="cover_letter_requested",
            field=models.BooleanField(default=False),
        ),
    ]
