# Generated by Django 5.2.7 on 2026-09-07 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumeApp", "0003_guestusage_analysis_level"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CVCreation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("location", models.CharField(blank=True, max_length=150)),
                ("linkedin", models.URLField(blank=True)),
                ("portfolio", models.URLField(blank=True)),
                ("professional_summary", models.TextField(blank=True)),
                ("work_experience", models.JSONField(default=list)),
                ("education", models.JSONField(default=list)),
                ("skills", models.JSONField(default=list)),
                ("projects", models.JSONField(default=list)),
                ("certifications", models.JSONField(default=list)),
                ("achievements", models.JSONField(default=list)),
                ("reference_cv_text", models.TextField(blank=True, null=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry Level"),
                            ("mid", "Mid Level"),
                            ("senior", "Senior Level"),
                            ("executive", "Executive"),
                        ],
                        default="mid",
                        max_length=10,
                    ),
                ),
                ("generated_cv", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cv_creations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CVRebuild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_cv_text", models.TextField()),
                ("rebuilt_cv", models.TextField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry Level"),
                            ("mid", "Mid Level"),
                            ("senior", "Senior Level"),
                            ("executive", "Executive"),
                        ],
                        default="mid",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rebuilds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
