# Generated by Django 5.2.7 on 2026-09-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumeApp", "0004_cvcreation_cvrebuild"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="rewritten_match_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="rewritten_score_breakdown",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="score_breakdown",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
