# Generated by Django 5.2.7 on 2026-09-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumeApp", "0005_analysis_rewritten_match_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="cover_letter_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("entry", "Entry Level"),
                    ("mid", "Mid Level"),
                    ("senior", "Senior Level"),
                    ("executive", "Executive"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="rewrite_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("entry", "Entry Level"),
                    ("mid", "Mid Level"),
                    ("senior", "Senior Level"),
                    ("executive", "Executive"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
